server:
  port: 8000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
      routes:
        - id: test1
          uri: lb://TEST1
          predicates:
            - Path=/api/test1/**
        - id: test2
          uri: lb://TEST2
          predicates:
            - Path=/api/test2/**

